// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class script001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(script001));
        
        string IMigrationMetadata.Id
        {
            get { return "202411140623505_script001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
